"""Chat/session index over Claude + Grok transcripts + a local organization overlay.

Claude writes append-only transcripts to ~/.claude/projects/<slug>/<id>.jsonl with
ai-title / last-prompt / gitBranch / pr-link records. Grok stores sessions under
~/.grok/sessions/<encoded-cwd>/<id>/ (summary.json + updates.jsonl). loom READS
those (never edits) to build a fast, cached index, and keeps its OWN overlay
(~/.loom/chats.json) for user-controlled state: star / archive / hide / name /
tags / description / agent.

Delete = soft-trash (overlay flag; transcripts stay for the native CLI).
Search depth = metadata + prompts (title, branch, PR, tags, description, first/last
prompt) — not full message bodies.
"""

from __future__ import annotations

import contextlib
import json
import os
import shutil
import uuid
from datetime import datetime
from pathlib import Path
from urllib.parse import unquote

from loom.core import agents
from loom.core import registry
from loom.core import repos as repos_mod
from loom.core.config import LOOM_HOME, ensure_dirs

CLAUDE_PROJECTS = Path.home() / ".claude" / "projects"
GROK_SESSIONS = Path.home() / ".grok" / "sessions"
TRASH_DIR = LOOM_HOME / "trash"
OVERLAY_PATH = LOOM_HOME / "chats.json"
INDEX_CACHE = LOOM_HOME / "sessions_index.json"


# --- small json helpers -------------------------------------------------------
def _read_json(path: Path, default):
    if path.exists():
        try:
            return json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            return default
    return default


def _write_json(path: Path, data) -> None:
    ensure_dirs()
    # Unique temp per writer: FastAPI serves these reads from a threadpool, so several
    # build_index() calls can write the cache at once. A shared "<name>.tmp" lets one
    # os.replace rename it away before another's runs → FileNotFoundError.
    tmp = path.with_suffix(path.suffix + f".{uuid.uuid4().hex}.tmp")
    try:
        tmp.write_text(json.dumps(data, indent=2, sort_keys=True))
        os.replace(tmp, path)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise


# --- overlay (user-owned state) ----------------------------------------------
# mtime/size-keyed cache of the parsed overlay. `get_overlay` was called once PER CHAT from
# `_merge` (so `list_chats` re-read + re-parsed chats.json N times per request) — a big GIL-bound
# cost that starved the terminal's event loop. Reads reuse this until the file changes.
_overlay_cache: tuple[tuple[float, int], dict] | None = None


def overlay_all() -> dict:
    global _overlay_cache
    try:
        st = OVERLAY_PATH.stat()
    except OSError:
        return {}
    key = (st.st_mtime, st.st_size)
    if _overlay_cache is not None and _overlay_cache[0] == key:
        return _overlay_cache[1]
    data = _read_json(OVERLAY_PATH, {})
    _overlay_cache = (key, data)
    return data


def get_overlay(sid: str) -> dict:
    return overlay_all().get(sid, {})


def set_overlay(sid: str, patch: dict) -> dict:
    global _overlay_cache
    data = _read_json(OVERLAY_PATH, {})  # fresh read → never mutate the cached dict in place
    cur = data.get(sid, {})
    cur.update(patch)
    data[sid] = cur
    _write_json(OVERLAY_PATH, data)
    _overlay_cache = None  # invalidate; next overlay_all() reloads what we just wrote
    return cur


# --- transcript parsing (metadata + prompts only) -----------------------------
# "User" records that are really Claude Code's local-command plumbing (/clear, /model,
# /effort, …), not something the user said. A session that STARTS with one (every
# /clear spawns a new session id whose first record is this marker) must not have it
# leak into first_prompt — that's how "<local-command-caveat…" junk chats appeared.
_LOCAL_CMD_MARKERS = (
    "<command-name>",
    "<local-command-stdout>",
    "<local-command-caveat>",
    "Caveat: The messages below were generated by the user while running local commands",
)


def _is_local_command_noise(text: str) -> bool:
    return any(m in text for m in _LOCAL_CMD_MARKERS)


def _extract_text(message) -> str | None:
    if not message:
        return None
    content = message.get("content") if isinstance(message, dict) else message
    if isinstance(content, str):
        return content[:240]
    if isinstance(content, list):
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                return (block.get("text") or "")[:240]
            if isinstance(block, str):
                return block[:240]
    return None


def _pr_from_record(rec: dict):
    for key in ("prNumber", "pr", "number"):
        if rec.get(key):
            return rec[key]
    url = rec.get("url") or rec.get("prUrl") or ""
    if "/pull/" in str(url):
        tail = str(url).rstrip("/").split("/pull/")[-1].split("/")[0]
        if tail.isdigit():
            return int(tail)
    return None


def _parse_transcript(path: Path) -> dict:
    title = preview = first_prompt = branch = cwd = created = pr_repo = None
    prs: set = set()
    n_user = n_assistant = 0
    try:
        with path.open("r", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                t = rec.get("type")
                if t == "ai-title":
                    title = rec.get("aiTitle") or title
                elif t == "last-prompt":
                    preview = rec.get("lastPrompt") or preview
                elif t == "pr-link":
                    pr = _pr_from_record(rec)
                    if pr:
                        prs.add(pr)
                    if rec.get("prRepository"):
                        pr_repo = rec["prRepository"]
                elif t in ("user", "assistant"):
                    if t == "user":
                        n_user += 1
                        if first_prompt is None:
                            text = _extract_text(rec.get("message"))
                            if text and not _is_local_command_noise(text):
                                first_prompt = text
                    else:
                        n_assistant += 1
                    if cwd is None and rec.get("cwd"):
                        cwd = rec.get("cwd")
                    if rec.get("gitBranch"):
                        branch = rec["gitBranch"]
                    if created is None and rec.get("timestamp"):
                        created = rec["timestamp"]
    except OSError:
        pass
    st = path.stat()
    return {
        "id": path.stem,
        "agent": "claude",
        "title": title,
        "preview": preview,
        "first_prompt": first_prompt,
        "branch": branch,
        "cwd": cwd,
        "prs": sorted(prs, key=str),
        "pr_repo": pr_repo,
        "created": created,
        "last_active": st.st_mtime,
        "size": st.st_size,
        "n_user": n_user,
        "n_assistant": n_assistant,
    }


def _parse_iso_ts(value: str | None) -> float | None:
    if not value:
        return None
    try:
        # Grok uses Z-suffixed UTC timestamps.
        return datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp()
    except (TypeError, ValueError):
        return None


def _parse_grok_session(sess_dir: Path, group_name: str) -> dict:
    """Index a Grok session directory from summary.json (+ light prompt peek)."""
    summary_path = sess_dir / "summary.json"
    title = preview = first_prompt = branch = cwd = created = None
    n_user = n_assistant = 0
    last_active = 0.0
    size = 0
    try:
        st = summary_path.stat()
        last_active = st.st_mtime
        size = st.st_size
        data = json.loads(summary_path.read_text())
        info = data.get("info") or {}
        cwd = info.get("cwd")
        title = data.get("generated_title") or data.get("session_summary")
        branch = data.get("head_branch")
        created = data.get("created_at")
        n_user = int(data.get("num_chat_messages") or 0) // 2  # rough; refined below
        n_assistant = int(data.get("num_chat_messages") or 0) - n_user
        la = _parse_iso_ts(data.get("last_active_at") or data.get("updated_at"))
        if la:
            last_active = la
    except (OSError, json.JSONDecodeError, TypeError, ValueError):
        pass
    if not cwd:
        # Decode the URL-encoded cwd group name (Grok's grouping key).
        with contextlib.suppress(Exception):
            cwd = unquote(group_name) or None
    # First / last user prompt from chat_history or the updates stream (best-effort, capped).
    # Skip system/developer rows — chat_history starts with a long system prompt that must
    # not leak into first_prompt / list previews.
    hist = sess_dir / "chat_history.jsonl"
    if hist.exists():
        try:
            with hist.open("r", errors="replace") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        rec = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    if not isinstance(rec, dict):
                        continue
                    role = (rec.get("type") or rec.get("role") or "").lower()
                    if role in ("system", "developer", "tool"):
                        continue
                    if role and role not in ("user", "human"):
                        continue
                    text = rec.get("display") or rec.get("text") or rec.get("prompt")
                    if not text and isinstance(rec.get("content"), str):
                        text = rec["content"]
                    if not text and isinstance(rec.get("message"), dict):
                        text = _extract_text(rec["message"])
                    if text and isinstance(text, str) and text.strip() and not _is_local_command_noise(text):
                        if first_prompt is None:
                            first_prompt = text[:240]
                        preview = text[:240]
        except OSError:
            pass
    # Prefer a short title-adjacent preview from updates (user_message_chunk) when history
    # didn't yield anything useful.
    try:
        ups = sess_dir / "updates.jsonl"
        if ups.exists():
            size = max(size, ups.stat().st_size)
            nu = na = 0
            with ups.open("r", errors="replace") as f:
                for line in f:
                    if "user_message" in line:
                        nu += 1
                        if first_prompt is None:
                            try:
                                rec = json.loads(line)
                                upd = ((rec.get("params") or {}).get("update") or {})
                                content = (upd.get("content") or {})
                                text = content.get("text") if isinstance(content, dict) else None
                                if text and isinstance(text, str) and text.strip():
                                    first_prompt = text[:240]
                                    preview = preview or first_prompt
                            except (json.JSONDecodeError, TypeError, AttributeError):
                                pass
                    elif "agent_message" in line:
                        na += 1
            if not n_user and not n_assistant:
                n_user, n_assistant = nu, na
    except OSError:
        pass
    return {
        "id": sess_dir.name,
        "agent": "grok",
        "title": title,
        "preview": preview,
        "first_prompt": first_prompt,
        "branch": branch,
        "cwd": cwd,
        "prs": [],
        "pr_repo": None,
        "created": created,
        "last_active": last_active,
        "size": size,
        "n_user": n_user,
        "n_assistant": n_assistant,
    }


def build_index(force: bool = False) -> list[dict]:
    """Re-parse only transcripts whose size/mtime changed; cache the rest.

    Cache keys are `claude:<id>` / `grok:<id>` so the two stores never collide.
    The public `id` field remains the raw session UUID.
    """
    cache = _read_json(INDEX_CACHE, {})
    out: dict[str, dict] = {}
    changed = force

    def _put(key: str, st_size: int, st_mtime: float, parse) -> None:
        nonlocal changed
        cached = cache.get(key)
        unchanged = (
            cached
            and not force
            and cached.get("size") == st_size
            and abs(cached.get("last_active", 0) - st_mtime) < 0.001
            # Re-parse if a pre-agent cache entry lacks the agent tag.
            and cached.get("agent")
        )
        if unchanged:
            out[key] = cached
        else:
            out[key] = parse()
            changed = True

    if CLAUDE_PROJECTS.exists():
        for proj in CLAUDE_PROJECTS.iterdir():
            if not proj.is_dir():
                continue
            for f in proj.glob("*.jsonl"):
                try:
                    st = f.stat()
                except OSError:
                    continue
                key = f"claude:{f.stem}"
                _put(key, st.st_size, st.st_mtime, lambda f=f: _parse_transcript(f))

    if GROK_SESSIONS.exists():
        for group in GROK_SESSIONS.iterdir():
            if not group.is_dir() or group.name.startswith("."):
                continue
            # Skip non-session files (e.g. session_search.sqlite lives at sessions root).
            try:
                children = list(group.iterdir())
            except OSError:
                continue
            for sess in children:
                if not sess.is_dir():
                    continue
                summary = sess / "summary.json"
                if not summary.exists():
                    continue
                try:
                    st = summary.stat()
                except OSError:
                    continue
                key = f"grok:{sess.name}"
                _put(
                    key,
                    st.st_size,
                    st.st_mtime,
                    lambda sess=sess, group=group: _parse_grok_session(sess, group.name),
                )

    # Only rewrite the cache when a transcript was added / removed / re-parsed. Under the
    # sidebar's polling this is usually a no-op, which avoids a concurrent-write storm.
    if changed or out.keys() != cache.keys():
        _write_json(INDEX_CACHE, out)
    return list(out.values())


# --- repo / task linkage ------------------------------------------------------
def _repo_task_for_cwd(cwd: str | None) -> tuple[str | None, str | None]:
    return _cwd_resolver()(cwd)


def _cwd_resolver():
    """Build a cwd → (repo, task_id) resolver ONCE. `list_chats` maps N chats through this;
    doing the registry/repo lookup per chat (the old `_repo_task_for_cwd`) re-read the task
    registry + repo list N times per request — the dominant cost of listing chats. Snapshot
    both lists here, then resolve each chat against the in-memory snapshot."""
    tasks = [(t.worktree_path.rstrip("/"), t.repo, t.id) for t in registry.list_tasks() if t.worktree_path]
    roots = [(r["root"].rstrip("/"), r["name"]) for r in repos_mod.list_repos()]

    def resolve(cwd: str | None) -> tuple[str | None, str | None]:
        if not cwd:
            return None, None
        for wp, repo, tid in tasks:
            if cwd == wp or cwd.startswith(wp + "/"):
                return repo, tid
        for root, name in roots:
            if cwd == root or cwd.startswith(root + "/"):
                return name, None
        return None, None

    return resolve


def _merge(s: dict, resolve=None) -> dict:
    ov = get_overlay(s["id"])
    repo_name, task_id = (resolve or _repo_task_for_cwd)(s.get("cwd"))
    title = ov.get("name") or s.get("title") or (s.get("first_prompt") or "")[:64] or s["id"][:8]
    # Overlay agent wins once locked; else the index source (claude/grok scan).
    agent = agents.normalize_agent(ov.get("agent") or s.get("agent"))
    return {
        **s,
        "agent": agent,
        "repo": repo_name,
        "task": task_id,
        "name": ov.get("name"),
        "display_title": title,
        "tags": ov.get("tags", []),
        "description": ov.get("description"),
        "pr_manual": ov.get("pr"),
        "starred": ov.get("starred", False),
        "archived": ov.get("archived", False),
        "hidden": ov.get("hidden", False),
        "deleted": ov.get("deleted", False),  # trashed = unlisted everywhere (transcript untouched)
        "mode": ov.get("mode"),  # "chat" | "terminal" | None (not yet chosen)
    }


def _is_contentless_junk(r: dict) -> bool:
    """A `/clear` (or other slash-command) offspring: a fresh session id whose only records are
    local-command plumbing — no overlay name, no ai-title, no first prompt, no preview, no
    assistant turn, AND at least one user record that's pure command noise (n_user > 0 while
    first_prompt stays None, e.g. the `<local-command-caveat>` + `<command-name>/clear` pair). Hide
    those; they'd list as a bare UUID and are noise.

    A brand-new session the user just opened but hasn't typed in yet has n_user == 0 — NOT junk.
    Keep it so it persists in the sidebar until the first message (a real prompt/reply also makes
    it non-empty and it stays on its own). Starred always survives."""
    if r.get("starred"):
        return False
    if r.get("name") or r.get("title") or r.get("first_prompt") or r.get("preview") or r.get("n_assistant"):
        return False
    return (r.get("n_user") or 0) > 0


def _haystack(r: dict) -> str:
    parts = [
        r.get("display_title", ""),
        r.get("title") or "",
        r.get("preview") or "",
        r.get("first_prompt") or "",
        r.get("branch") or "",
        r.get("description") or "",
        " ".join(map(str, r.get("tags", []))),
        " ".join(map(str, r.get("prs", []))),
        str(r.get("pr_manual") or ""),
    ]
    return " ".join(parts).lower()


def _pending_chat_rows(indexed_ids: set, resolve) -> list[dict]:
    """Chats loom has OPENED (their overlay carries `opened_at`) but that have no transcript yet.
    claude writes nothing until the first message, so a just-opened, not-yet-typed chat is absent
    from the index and would vanish from the sidebar the moment you click away. Surface a synthetic
    row for each so it persists; the real indexed row takes over once the first message lands.
    Only OPENED overlays qualify (a task's chat gets mode:terminal at create time too — opened_at
    is written solely when a terminal actually attaches), so this never floods with never-opened
    task chats."""
    task_by_chat = {t.chat_id: t for t in registry.list_tasks() if t.chat_id}
    out = []
    for cid, ov in overlay_all().items():
        if cid in indexed_ids or not ov.get("opened_at"):
            continue
        if ov.get("deleted") or ov.get("archived") or ov.get("hidden"):
            continue
        t = task_by_chat.get(cid)
        out.append(_merge({
            "id": cid, "agent": ov.get("agent"),
            # Fall back to the branch name so a not-yet-typed chat reads as its worktree, not a
            # bare UUID; the real ai-title/first-prompt replaces it once the first message lands.
            "title": (t.branch if t else None), "preview": None, "first_prompt": None,
            "branch": (t.branch if t else None), "cwd": (t.worktree_path if t else None),
            "prs": [], "pr_repo": None, "created": None,
            "last_active": float(ov.get("opened_at") or 0.0), "size": 0,
            "n_user": 0, "n_assistant": 0,
        }, resolve))
    return out


def list_chats(
    repo: str | None = None,
    scope: str = "repo",
    tab: str = "active",
    q: str | None = None,
    branch: str | None = None,
    starred: bool | None = None,
) -> list[dict]:
    resolve = _cwd_resolver()  # snapshot task/repo lists once, not once per chat
    indexed = [_merge(s, resolve) for s in build_index()]
    # Keep just-opened, not-yet-typed chats visible (they have no transcript yet — see above).
    rows = indexed + _pending_chat_rows({r["id"] for r in indexed}, resolve)
    # Trashed chats are unlisted in every tab (the transcript itself is untouched — see
    # trash_chat; now that trashing no longer moves the file, the index still sees it).
    rows = [r for r in rows if not r["deleted"]]
    # Drop /clear-offspring & empty aborted sessions (bare-UUID, zero human content) — see
    # _is_contentless_junk. They'd otherwise clutter the list and invite a misclick that opens
    # an orphan session.
    rows = [r for r in rows if not _is_contentless_junk(r)]

    if scope == "repo" and repo:
        rows = [r for r in rows if r["repo"] == repo]
    if tab == "active":
        rows = [r for r in rows if not r["archived"] and not r["hidden"]]
    elif tab == "archived":
        rows = [r for r in rows if r["archived"]]
    elif tab == "hidden":
        rows = [r for r in rows if r["hidden"]]
    if starred:
        rows = [r for r in rows if r["starred"]]
    if branch:
        rows = [r for r in rows if (r.get("branch") or "") == branch]
    if q:
        ql = q.lower()
        rows = [r for r in rows if ql in _haystack(r)]

    rows.sort(key=lambda r: (not r["starred"], -r["last_active"]))
    return rows


def get_chat(sid: str) -> dict | None:
    return next((s for s in build_index() if s["id"] == sid), None)


def get_transcript(sid: str) -> list[dict]:
    """Reconstruct a session's conversation as render-ready chat items.

    user(string) -> user message; assistant -> text + thinking + tool_use blocks;
    user(tool_result) -> attaches result to the matching tool by tool_use_id.
    """
    path = _find_transcript(sid)
    if not path or not path.exists():
        return []
    items: list[dict] = []
    tool_index: dict = {}
    with path.open(errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            t = rec.get("type")
            if t == "user":
                content = (rec.get("message") or {}).get("content")
                if isinstance(content, str):
                    if content.strip():
                        items.append({"kind": "user", "text": content})
                elif isinstance(content, list):
                    tool_results = [b for b in content if isinstance(b, dict) and b.get("type") == "tool_result"]
                    if tool_results:
                        for b in tool_results:
                            tool = tool_index.get(b.get("tool_use_id"))
                            if tool is not None:
                                c = b.get("content")
                                if isinstance(c, list):
                                    c = "\n".join(
                                        (x.get("text") or "") if isinstance(x, dict) else str(x) for x in c
                                    )
                                tool["result"] = c if isinstance(c, str) else ("" if c is None else str(c))
                                tool["isError"] = b.get("is_error")
                    else:
                        # A real user message with text/image blocks (e.g. a pasted image).
                        txt = "\n".join(
                            b.get("text", "") for b in content
                            if isinstance(b, dict) and b.get("type") == "text" and b.get("text")
                        )
                        imgs = []
                        for b in content:
                            if isinstance(b, dict) and b.get("type") == "image":
                                src = b.get("source") or {}
                                if src.get("type") == "base64" and src.get("data"):
                                    imgs.append({"media_type": src.get("media_type") or "image/png", "data": src["data"]})
                        if txt or imgs:
                            item = {"kind": "user", "text": txt}
                            if imgs:
                                item["images"] = imgs
                            items.append(item)
            elif t == "assistant":
                content = (rec.get("message") or {}).get("content") or []
                if rec.get("isApiErrorMessage"):
                    # Claude Code records a mid-turn API failure (timeout, dropped socket,
                    # overload) as a synthetic assistant message — surface it as a clear
                    # error on resume/refresh, not as a normal reply.
                    etxt = " ".join(
                        b.get("text", "") for b in content
                        if isinstance(b, dict) and b.get("type") == "text"
                    ).strip()
                    items.append({"kind": "error", "text": "⚠ API error — the turn stopped early: " + (etxt or "unknown error")})
                else:
                    texts, thinks, tools = [], [], []
                    for b in content:
                        if not isinstance(b, dict):
                            continue
                        bt = b.get("type")
                        if bt == "text":
                            texts.append(b.get("text", ""))
                        elif bt == "thinking":
                            thinks.append(b.get("thinking", ""))
                        elif bt == "tool_use":
                            tool = {"id": b.get("id"), "name": b.get("name"), "input": b.get("input")}
                            tools.append(tool)
                            tool_index[b.get("id")] = tool
                    if texts or thinks or tools:
                        items.append({
                            "kind": "assistant",
                            "text": "".join(texts),
                            "thinking": "".join(thinks),
                            "tools": tools,
                        })
    return items


# --- trash (soft delete) ------------------------------------------------------
def _find_transcript(sid: str) -> Path | None:
    """Locate a Claude transcript jsonl (legacy name — used by get_transcript).

    Grok sessions are directories, not single jsonl files; get_transcript only
    reconstructs Claude's format today. Prefer agents.find_* for existence checks.
    """
    found = agents.find_claude_transcript(sid)
    if found:
        return found
    return None


def trash_chat(sid: str) -> None:
    """Unregister a chat from loom — overlay flag ONLY.

    The transcript under ~/.claude/projects is the user's history and is NEVER
    moved, deleted, or modified by loom (it stays fully usable by `claude
    --resume`, ~/.claude tooling, etc.); trashing just stops loom from listing
    the chat. (The old behavior moved the jsonl into ~/.loom/trash — files
    already there are still restorable via restore_chat's legacy path.)"""
    set_overlay(sid, {"deleted": True})


def restore_chat(sid: str) -> None:
    src = TRASH_DIR / f"{sid}.jsonl"
    orig = get_overlay(sid).get("orig_dir")
    if src.exists() and orig:
        Path(orig).mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(Path(orig) / f"{sid}.jsonl"))
    set_overlay(sid, {"deleted": False})


def list_trash() -> list[str]:
    TRASH_DIR.mkdir(parents=True, exist_ok=True)
    return [p.stem for p in TRASH_DIR.glob("*.jsonl")]


def empty_trash() -> None:
    if TRASH_DIR.exists():
        for p in TRASH_DIR.glob("*.jsonl"):
            p.unlink()
